/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basic_kalkulator;

import javax.swing.JOptionPane;

/**
 *
 * @author NIOKE
 */
public class basic_calkulator extends javax.swing.JFrame {

    /**
     * Creates new form basic_calkulator
     */
    Double num,ans;
    boolean tekan = false;
    int calculation;
    public basic_calkulator() {
        initComponents();
    }

    
    public void aritmathic_operation(){
        
        switch(calculation){
            case 1: //addition
                ans = num + Double.parseDouble(tf_Result.getText());
                tf_Result.setText(Double.toString(ans));
                break;            
             case 2: //subtraction
                ans = num - Double.parseDouble(tf_Result.getText());
                tf_Result.setText(Double.toString(ans));
                break;  
            case 3: //Multiplication
                ans = num * Double.parseDouble(tf_Result.getText());
                tf_Result.setText(Double.toString(ans));
                break;
            case 4: //Division
                ans = num / Double.parseDouble(tf_Result.getText());
                tf_Result.setText(Double.toString(ans));
                break;  
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_CE = new javax.swing.JButton();
        btn_Hapus = new javax.swing.JButton();
        btn_Plus = new javax.swing.JButton();
        btn_Minus = new javax.swing.JButton();
        btn_Kali = new javax.swing.JButton();
        btn_Bagi = new javax.swing.JButton();
        btn_Angka_Tujuh = new javax.swing.JButton();
        btn_Angka_Delapan = new javax.swing.JButton();
        btn_Angka_Sembilan = new javax.swing.JButton();
        btn_Angka_Empat = new javax.swing.JButton();
        btn_Angka_Lima = new javax.swing.JButton();
        btn_Angka_Enam = new javax.swing.JButton();
        btn_Angka_Satu = new javax.swing.JButton();
        btn_Angka_Dua = new javax.swing.JButton();
        btn_Angka_Tiga = new javax.swing.JButton();
        btn_Angka_nul = new javax.swing.JButton();
        btn_Koma = new javax.swing.JButton();
        btn_SamaDengan = new javax.swing.JButton();
        tf_Result = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setText("MY CALCULATOR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 0, -1, -1));

        btn_CE.setText("CE");
        btn_CE.setPreferredSize(new java.awt.Dimension(95, 45));
        btn_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CEActionPerformed(evt);
            }
        });
        jPanel1.add(btn_CE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 194, -1, -1));

        btn_Hapus.setText("<--");
        btn_Hapus.setPreferredSize(new java.awt.Dimension(95, 45));
        btn_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HapusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 194, -1, -1));

        btn_Plus.setText("+");
        btn_Plus.setPreferredSize(new java.awt.Dimension(95, 45));
        btn_Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PlusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 194, -1, -1));

        btn_Minus.setText("-");
        btn_Minus.setPreferredSize(new java.awt.Dimension(95, 45));
        btn_Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MinusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 245, -1, -1));

        btn_Kali.setText("x");
        btn_Kali.setPreferredSize(new java.awt.Dimension(95, 45));
        btn_Kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KaliActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Kali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 245, -1, -1));

        btn_Bagi.setText("/");
        btn_Bagi.setPreferredSize(new java.awt.Dimension(95, 45));
        btn_Bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BagiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Bagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 245, -1, -1));

        btn_Angka_Tujuh.setText("7");
        btn_Angka_Tujuh.setPreferredSize(new java.awt.Dimension(95, 45));
        btn_Angka_Tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Angka_TujuhActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Angka_Tujuh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 296, -1, -1));

        btn_Angka_Delapan.setText("8");
        btn_Angka_Delapan.setPreferredSize(new java.awt.Dimension(95, 45));
        btn_Angka_Delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Angka_DelapanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Angka_Delapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 296, -1, -1));

        btn_Angka_Sembilan.setText("9");
        btn_Angka_Sembilan.setPreferredSize(new java.awt.Dimension(95, 45));
        btn_Angka_Sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Angka_SembilanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Angka_Sembilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 296, -1, -1));

        btn_Angka_Empat.setText("4");
        btn_Angka_Empat.setPreferredSize(new java.awt.Dimension(95, 45));
        btn_Angka_Empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Angka_EmpatActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Angka_Empat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 347, -1, -1));

        btn_Angka_Lima.setText("5");
        btn_Angka_Lima.setPreferredSize(new java.awt.Dimension(95, 45));
        btn_Angka_Lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Angka_LimaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Angka_Lima, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 347, -1, -1));

        btn_Angka_Enam.setText("6");
        btn_Angka_Enam.setPreferredSize(new java.awt.Dimension(95, 45));
        btn_Angka_Enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Angka_EnamActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Angka_Enam, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 347, -1, -1));

        btn_Angka_Satu.setText("1");
        btn_Angka_Satu.setPreferredSize(new java.awt.Dimension(95, 45));
        btn_Angka_Satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Angka_SatuActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Angka_Satu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 398, -1, -1));

        btn_Angka_Dua.setText("2");
        btn_Angka_Dua.setPreferredSize(new java.awt.Dimension(95, 45));
        btn_Angka_Dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Angka_DuaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Angka_Dua, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 398, -1, -1));

        btn_Angka_Tiga.setText("3");
        btn_Angka_Tiga.setPreferredSize(new java.awt.Dimension(95, 45));
        btn_Angka_Tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Angka_TigaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Angka_Tiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 398, -1, -1));

        btn_Angka_nul.setText("0");
        btn_Angka_nul.setPreferredSize(new java.awt.Dimension(95, 45));
        btn_Angka_nul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Angka_nulActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Angka_nul, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 449, -1, -1));

        btn_Koma.setText(",");
        btn_Koma.setPreferredSize(new java.awt.Dimension(95, 45));
        btn_Koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KomaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Koma, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 449, -1, -1));

        btn_SamaDengan.setText("=");
        btn_SamaDengan.setPreferredSize(new java.awt.Dimension(95, 45));
        btn_SamaDengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SamaDenganActionPerformed(evt);
            }
        });
        jPanel1.add(btn_SamaDengan, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 449, -1, -1));

        tf_Result.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(tf_Result, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 301, 112));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 80, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PlusActionPerformed
        // TODO add your handling code here:
        num = Double.parseDouble(tf_Result.getText());
        calculation = 1;
        tf_Result.setText("");
        jLabel2.setText(num + "+");
    }//GEN-LAST:event_btn_PlusActionPerformed

    private void btn_KaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KaliActionPerformed
        // TODO add your handling code here:
        num = Double.parseDouble(tf_Result.getText());
        calculation = 3;
        tf_Result.setText("");
        jLabel2.setText(num + "*");
    }//GEN-LAST:event_btn_KaliActionPerformed

    private void btn_BagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BagiActionPerformed
        // TODO add your handling code here:
        num = Double.parseDouble(tf_Result.getText());
        calculation = 4;
        tf_Result.setText("");
        jLabel2.setText(num + "/");
    }//GEN-LAST:event_btn_BagiActionPerformed

    private void btn_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CEActionPerformed
        // TODO add your handling code here:
        tf_Result.setText("");
    }//GEN-LAST:event_btn_CEActionPerformed

    private void btn_Angka_TujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Angka_TujuhActionPerformed
        // TODO add your handling code here:
        if (tekan == true) {
            tf_Result.setText("");
            tekan = false;
        }
        tf_Result.setText(tf_Result.getText() + "7");
    }//GEN-LAST:event_btn_Angka_TujuhActionPerformed

    private void btn_Angka_DelapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Angka_DelapanActionPerformed
        // TODO add your handling code here:
        if (tekan == true) {
            tf_Result.setText("");
            tekan = false;
        }
        tf_Result.setText(tf_Result.getText() + "8");
    }//GEN-LAST:event_btn_Angka_DelapanActionPerformed

    private void btn_Angka_SembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Angka_SembilanActionPerformed
        // TODO add your handling code here:
        if (tekan == true) {
            tf_Result.setText("");
            tekan = false;
        }
        tf_Result.setText(tf_Result.getText() + "9");
    }//GEN-LAST:event_btn_Angka_SembilanActionPerformed

    private void btn_Angka_EmpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Angka_EmpatActionPerformed
        // TODO add your handling code here:
        if (tekan == true) {
            tf_Result.setText("");
            tekan = false;
        }
            tf_Result.setText(tf_Result.getText() + "4");
       
    }//GEN-LAST:event_btn_Angka_EmpatActionPerformed

    private void btn_Angka_LimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Angka_LimaActionPerformed
        // TODO add your handling code here:
        if (tekan == true) {
            tf_Result.setText("");
            tekan = false;
        }
        tf_Result.setText(tf_Result.getText() + "5");
    }//GEN-LAST:event_btn_Angka_LimaActionPerformed

    private void btn_Angka_EnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Angka_EnamActionPerformed
        // TODO add your handling code here:
        if (tekan == true) {
            tf_Result.setText("");
            tekan = false;
        }
        tf_Result.setText(tf_Result.getText() + "6");
    }//GEN-LAST:event_btn_Angka_EnamActionPerformed

    private void btn_Angka_SatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Angka_SatuActionPerformed
        // TODO add your handling code here:
        if (tekan == true) {
            tf_Result.setText("");
            tekan = false;
        }
        tf_Result.setText(tf_Result.getText() + "1");
    }//GEN-LAST:event_btn_Angka_SatuActionPerformed

    private void btn_Angka_DuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Angka_DuaActionPerformed
        // TODO add your handling code here:
        if (tekan == true) {
            tf_Result.setText("");
            tekan = false;
        }
        tf_Result.setText(tf_Result.getText() + "2");
    }//GEN-LAST:event_btn_Angka_DuaActionPerformed

    private void btn_Angka_TigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Angka_TigaActionPerformed
        // TODO add your handling code here:
        if (tekan == true) {
            tf_Result.setText("");
            tekan = false;
        }
        tf_Result.setText(tf_Result.getText() + "3");
    }//GEN-LAST:event_btn_Angka_TigaActionPerformed

    private void btn_Angka_nulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Angka_nulActionPerformed
        // TODO add your handling code here:
        if (tekan == true) {
            tf_Result.setText("");
            tekan = false;
        }
        tf_Result.setText(tf_Result.getText() + "0");
    }//GEN-LAST:event_btn_Angka_nulActionPerformed

    private void btn_KomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KomaActionPerformed
        // TODO add your handling code here:
        String res = tf_Result.getText();
        String[] kd = res.split(res);
        if (res.contains(".")) {
            JOptionPane.showMessageDialog(this, "Error bro");
            tf_Result.setText("");
        } else {
            tf_Result.setText(tf_Result.getText() + ".");
        }
    }//GEN-LAST:event_btn_KomaActionPerformed

    private void btn_MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MinusActionPerformed
        // TODO add your handling code here:
        num = Double.parseDouble(tf_Result.getText());
        calculation = 2;
        tf_Result.setText("");
        jLabel2.setText(num + "-");
    }//GEN-LAST:event_btn_MinusActionPerformed

    private void btn_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HapusActionPerformed
        // TODO add your handling code here:
        int length = tf_Result.getText().length();
        int number = tf_Result.getText().length() - 1;
        String store;
        if (length > 0) {
            StringBuilder back = new StringBuilder(tf_Result.getText());
            back.deleteCharAt(number);
            store = back.toString();
            tf_Result.setText(store);
        }
    }//GEN-LAST:event_btn_HapusActionPerformed

    private void btn_SamaDenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SamaDenganActionPerformed
        // TODO add your handling code here:
        aritmathic_operation();
        jLabel2.setText("");
        tekan = true;
    }//GEN-LAST:event_btn_SamaDenganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(basic_calkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(basic_calkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(basic_calkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(basic_calkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new basic_calkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Angka_Delapan;
    private javax.swing.JButton btn_Angka_Dua;
    private javax.swing.JButton btn_Angka_Empat;
    private javax.swing.JButton btn_Angka_Enam;
    private javax.swing.JButton btn_Angka_Lima;
    private javax.swing.JButton btn_Angka_Satu;
    private javax.swing.JButton btn_Angka_Sembilan;
    private javax.swing.JButton btn_Angka_Tiga;
    private javax.swing.JButton btn_Angka_Tujuh;
    private javax.swing.JButton btn_Angka_nul;
    private javax.swing.JButton btn_Bagi;
    private javax.swing.JButton btn_CE;
    private javax.swing.JButton btn_Hapus;
    private javax.swing.JButton btn_Kali;
    private javax.swing.JButton btn_Koma;
    private javax.swing.JButton btn_Minus;
    private javax.swing.JButton btn_Plus;
    private javax.swing.JButton btn_SamaDengan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_Result;
    // End of variables declaration//GEN-END:variables
}
